# Generated by Django 5.1.4 on 2025-01-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0006_bookissue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookissue',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='bookissue',
            old_name='student',
            new_name='student_id',
        ),
    ]
