# Generated by Django 5.1.4 on 2025-01-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0007_rename_book_bookissue_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookissue',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookissue',
            old_name='student_id',
            new_name='student',
        ),
    ]
