# Generated by Django 5.1.4 on 2025-01-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0011_finepaymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.student')),
            ],
        ),
    ]
