# Generated by Django 5.1.4 on 2025-01-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0012_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issued_date',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
