# Generated by Django 5.1.4 on 2025-01-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0013_remove_issue_issued_date_issue_issue_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
