# Generated by Django 5.1.4 on 2025-01-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0014_delete_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finepaymenttransaction',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='remaining_amount',
        ),
        migrations.DeleteModel(
            name='FinePayment',
        ),
        migrations.DeleteModel(
            name='FinePaymentTransaction',
        ),
    ]
