# Generated by Django 5.1.4 on 2025-01-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0016_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='fix_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
